baseURL = "https://wwucyber.github.io/"

languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = false
  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "WWU Cybersecurity Club"
    subtitle = "The homepage of the Western Washington University Cybersecurity Club"
    keywords = "wwu, western, cybersecurity, security, infosec, compsci"
    copyright = "WWU Cybersecurity Club"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "WWU Cybersecurity"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
